# -*- coding: utf-8 -*-
"""Imersão Dados Alura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzX_foW0Kd5_ct6U6zd9Jd2DL5aUgPH6

# **Aula 01**

### Biblioteca
"""

import pandas as pd

"""### Data Set a ser usado"""

url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"
dados = pd.read_csv(url)

dados.head()

"""### Descrição de dados que temos na tabela"""

dados.info()

"""### Variável de um único Bairro"""

imoveis_vilaMariana = (dados.Bairro == 'Vila Mariana')
imoveis_vilaMariana

"""### Tabela de acordo com variável declarada anteriormente"""

imoveisVM = dados[imoveis_vilaMariana]
imoveisVM

"""### Quantidade de imóveis por Bairro"""

dados["Bairro"].value_counts()

"""### Variável mantém valor total dos imóveis de acordo com cada Bairro"""

n_imoveis_bairro = dados.Bairro.value_counts()

"""### Gráfico com os 5 mais populosos de SP"""

n_imoveis_bairro.head(5).plot.bar()

"""# **Desafios 01**

## 1 - Realizar a média da metragem para cara um dos bairros (Paulo)

Média de cada um dos bairros
"""

dados.groupby('Bairro')['Metragem'].mean()

"""## 2 - 2 formas de selecionar os dados por bairro (consultar os métodos na documentação do pandas) (Thiago)

Selecionando o Bairro usando index [coluna] [linha]
"""

dados["Bairro"][4322]

"""Mesma seleção de outra forma"""

dados.Bairro[6022]

"""Localizando um imóvel aleatório no bairro de Interlágos"""

dados[dados["Bairro"] == 'Interlagos'].sample()

"""## 3 - Explorar alguns gráficos na documentação e aplicar nas demais colunas do DF, tentar colocar alguma conclusão (Thiago)

**Mais quartos, mais caro?**
"""

dados['Valor'] = dados['Valor'].str.replace('$', '').str.replace('R', '')
dados.head(10).plot.bar(x='Valor', y='Quartos')

"""Observa-se que não há relação de que quanto mais cômodos, mais caro seja

## 4 - Pegar outros estatísticas dos dados, média, mediana, mim, max (Vivi)
"""

# Média
mdDados = dados.Metragem.mean()
# Mediana
mdnDados = dados.Metragem.median()
# Mínima
minDados = dados.Metragem.min()
# Máxima
maxDados = dados.Metragem.max()

print(f'Média: {mdDados} | Mediana: {mdnDados} | Mínina: {minDados} | Máxima: {maxDados}')

"""## 5 - Descobrir quais são os bairros que não tem nome de Rua. (Vivi)

*Descobrir o total de valores nulos*
"""

dados.isnull().sum()

"""*Variável para isolar bairros que não tem nome de Rua cadastrado*"""

sem_rua = dados[dados['Rua'].isnull()]
sem_rua['Bairro'].value_counts()

"""*Mostrar quais linhas não possuem valores em Bairro*"""

sem_bairro = dados[dados['Bairro'].isnull()]
sem_bairro.head(12)

